### ISSUE TITLE
Setup pinger to maintain webring

### ISSUE THREAD

**Issue by KhushrajRathod** [hackclub/webring#43]
Webring sites keep going down :(

Here's what I feel is a solution -- Periodically scrape all webring sites 

- If a non 2xx code is returned, or
- If the site does not contain the webring code

temporarily kick the member from the webring (until next scrape)

**Comment by sampoder** [comment]
Would GitHub actions work for this?

**Comment by KhushrajRathod** [comment]
I think so -- should I give it a shot?

**Comment by KhushrajRathod** [comment]
There'll need to be a separate database apart from the approved webring members, to store the "current webring members"

**Comment by sampoder** [comment]
That'd be awesome @KhushrajRathod, let's wait for @googol88's input here though.

> There'll need to be a separate database apart from the approved webring members, to store the "current webring members"

Could we simply comment out JSON?

**Comment by KhushrajRathod** [comment]
> Could we simply add a field to the JSON?

That'd require committing to git from every actions run

**Comment by sampoder** [comment]
Yep

**Comment by googol88** [comment]
Hi y'all this is looking pretty neat! I'm thinking a database isn't strictly required, but it would be slightly easier for contributors to add their own site to the webring without the extra JSON field. But that's not really important anyway, my main point is that we'd probably be better off using sam's idea since overall I think it's simpler. I never would have thought of doing this myself, thanks for bringing this up @KhushrajRathod!

**Comment by KhushrajRathod** [comment]
Cool. I'll make a PR soon

**Comment by KhushrajRathod** [comment]
@googol88 https://github.com/hackclub/webring/pull/44
