### ISSUE TITLE
New GitHub Workflow Doesn't Support API

### ISSUE THREAD

**Issue by sampoder** [hackclub/webring#45]
The workflow doesn't support @rishiosaur's API :/ 

Temporary fix is in place

View: https://github.com/rishiosaur/webring-api

**Comment by sampoder** [comment]
cc: @KhushrajRathod

**Comment by KhushrajRathod** [comment]
Hmm... I'm not sure how I'd go about implementing this, since its completely done by JavaScript. It's also not very obvious how the webring works on rishi's site. Since a redesign is coming up (next.rishi.cx), maybe just stick to the webring code? I can recognise the webring controls by the hack club logo and the two arrows, but not so much in custom designs
